//! `docs/agents.md` host table is generated from the host code, so it cannot drift.
//!
//! Check: the block between the `agents-table` markers equals what `HOSTS`, `Agent::variants`,
//! `Agent::support` and the plugin catalogue say today. After changing a host or a plugin's
//! surfaces, regenerate with `RTOK_BLESS=1 mise exec -- cargo test --test agents_doc`.

use std::fs;
use std::path::PathBuf;

use rtok::agents::{self, HOSTS, MODULES, Support};
use rtok::config::Config;
use rtok::plugins::Registry;

const START: &str = "<!-- agents-table:start (generated by tests/agents_doc.rs) -->\n";
const END: &str = "<!-- agents-table:end -->\n";

fn cell(s: Support) -> String {
    match s {
        Support::Yes => "yes".into(),
        Support::Flag(flag) | Support::Offer(flag) => format!("`{flag}`"),
        Support::No(_) => "—".into(),
    }
}

fn table() -> String {
    let cfg = Config::default();
    let manifests = Registry::new(&cfg).manifests();
    let mut out = String::from(
        "| Host | App | Kind | Hooks | MCP | Proxy | Plugin | rtok plugins reached |\n\
         | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for id in HOSTS {
        let agent = agents::host(id).expect("host in HOSTS");
        for v in agent.variants() {
            let modules: Vec<String> = MODULES
                .iter()
                .map(|m| cell(agent.support(v.kind, m)))
                .collect();
            let reached: Vec<String> = manifests
                .iter()
                .filter(|(m, _)| agents::reaches(agent, v.kind, m.surfaces))
                .map(|(m, on)| {
                    if *on {
                        m.id.to_string()
                    } else {
                        format!("{} (off)", m.id)
                    }
                })
                .collect();
            let reached = if reached.is_empty() {
                "—".to_string()
            } else {
                reached.join(", ")
            };
            out.push_str(&format!(
                "| [`{id}`](https://github.com/listepo/rtok/blob/main/src/agents/{id}/README.md) | {} | {} | {} | {reached} |\n",
                v.name,
                v.kind.label(),
                modules.join(" | "),
            ));
        }
    }
    out
}

#[test]
fn agents_doc_table_matches_the_host_code() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("docs/agents.md");
    let doc = fs::read_to_string(&path).expect("docs/agents.md");
    let (head, rest) = doc.split_once(START).expect("start marker");
    let (old, tail) = rest.split_once(END).expect("end marker");
    let new = table();
    if old == new {
        return;
    }
    if std::env::var_os("RTOK_BLESS").is_some() {
        fs::write(&path, format!("{head}{START}{new}{END}{tail}")).unwrap();
        return;
    }
    panic!(
        "docs/agents.md host table is stale; run `RTOK_BLESS=1 mise exec -- cargo test --test agents_doc`\n\
         --- doc\n{old}--- code\n{new}"
    );
}
